project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from welcome.views import index, health
from linewashapp.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', home),
    url(r'^add', add),
    url(r'^show', show),
    url(r'^edit/(\d+)/', edit, name = 'id'),
    url(r'^update/(\d+)/', update, name = 'id'),
    url(r'^delete/(\d+)/', delete, name = 'id'),

    url(r'^edit/car/(\d+)/', editCar, name = 'id'),
    url(r'^update/car/(\d+)/', updateCar, name = 'id'),
    
    url(r'^edit/client/(\d+)/', editClient, name = 'id'),
    url(r'^update/client/(\d+)/', updateClient, name = 'id'),

    url(r'^price/(\d+)/(\d+)/(\d+)/', price),

    url(r'^test/', bootstrapHome),
    url(r'^health$', health),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), {'next_page': '/'}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

linewashapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class PageView(models.Model):
    hostname = models.CharField(max_length = 50)
    timestamp = models.DateTimeField(auto_now_add = True)

class ClientType(models.Model):
    name = models.CharField(max_length = 100, null = True, blank = True)
    def  __str__(self):
        return self.name

class ServiceType(models.Model):
    name = models.CharField(max_length = 100, null = True, blank = True)
    def  __str__(self):
        return self.name

class CarType(models.Model):
    name = models.CharField(max_length = 100, null = True, blank = True)
    def  __str__(self):
        return self.name

class PaymentType(models.Model):
    name = models.CharField(max_length = 100, null = True, blank = True)
    def  __str__(self):
        return self.name

class Price(models.Model):
    clientType = models.ForeignKey(ClientType, null = True, blank = True, verbose_name = "ClientType", on_delete = models.SET_NULL)
    serviceType = models.ForeignKey(ServiceType, null = True, blank = True, verbose_name = "ServiceType", on_delete = models.SET_NULL)
    carType = models.ForeignKey(CarType, null = True, blank = True, verbose_name = "CarType", on_delete = models.SET_NULL)
    price = models.FloatField(null = True, blank = True)
    def  __str__(self):
        return self.name

class Car(models.Model):
    brand = models.CharField(max_length = 50, null = True, blank = True) 
    model = models.CharField(max_length = 50, null = True, blank = True)
    plate = models.CharField(max_length = 20,unique = True)
    carType = models.ForeignKey(CarType, null = True, blank = True, verbose_name = "CarType", on_delete = models.SET_NULL)
    class Meta:
        db_table = "car"

class Client(models.Model):
    phone = models.CharField(max_length = 50, unique = True, null = True, blank = True)
    name = models.CharField(max_length = 50, null = True, blank = True)
    birthday = models.CharField(max_length = 50, null = True, blank = True)
    nif = models.CharField(max_length = 50,unique = True, null = True, blank = True)
    email = models.CharField(max_length = 50, null = True, blank = True)
    address = models.CharField(max_length = 400, null = True, blank = True)
    class Meta:
        db_table = "client"

class Wash(models.Model):
    timestamp = models.DateTimeField(default = timezone.now,blank = True)
    price = models.FloatField(null = True, blank = True)
    tip = models.FloatField(default = 0,null = True, blank = True)
    finalClient = models.BooleanField(default = True,blank = True)
    payed = models.BooleanField(default = True,blank = True)
    comments = models.CharField(max_length = 1000, null = True, blank = True)
    car = models.ForeignKey(Car, null = True, blank = True, verbose_name = "Car", on_delete = models.SET_NULL)
    client = models.ForeignKey(Client, null = True, blank = True, verbose_name = "Client", on_delete = models.SET_NULL)
    paymentType = models.ForeignKey(PaymentType, null = True, blank = True, verbose_name = "PaymentType", on_delete = models.SET_NULL)
    clientType = models.ForeignKey(ClientType, null = True, blank = True, verbose_name = "ClientType", on_delete = models.SET_NULL)
    serviceType = models.ForeignKey(ServiceType, null = True, blank = True, verbose_name = "ServiceType", on_delete = models.SET_NULL)
    class Meta:
        db_table = "wash"

linewashapp/forms.py
from django import forms  
from linewashapp.models import Wash, Car, Client

class WashForm(forms.ModelForm):  
    class Meta:  
        model = Wash
        fields = "__all__"
        widgets = {
            'paymentType': forms.Select(attrs={'class': 'custom-select d-block w-100'}),
            'clientType': forms.Select(attrs={'class': 'custom-select d-block w-100 price-update'}),
            'serviceType': forms.Select(attrs={'class': 'custom-select d-block w-100 price-update'}),
        }

class CarForm(forms.ModelForm):  
    class Meta:  
        model = Car
        fields = "__all__"
        widgets = {
            'carType': forms.Select(attrs={'class': 'custom-select d-block w-100 price-update'}),
        }

class ClientForm(forms.ModelForm):  
    class Meta:  
        model = Client
        fields = "__all__"

linewashapp/views.py
import os
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import HttpResponse, QueryDict, JsonResponse

from datetime import datetime

from . import database
from .models import PageView

from django.contrib.auth.decorators import login_required

from linewashapp.forms import WashForm, ClientForm, CarForm
from linewashapp.models import *

# Create your views here.

def getCurrentDate():
   now = datetime.now()
#    dt_string = now.strftime("%d/%m/%Y %H:%M")
   dt_string = now.strftime("%Y-%m-%d %H:%M")
   return dt_string

def getCarBrands():
	return ["Alfa Romeo", "Aston Martin", "Audi", "Bentley", "BMW", "Bugatti", "Cadillac", "Chevrolet", "Chrysler", "Citroen", "Corvette", "DAF", "Dacia", "Daewoo", "Daihatsu", "Datsun", "Dino", "Dodge", "Farboud", "Ferrari", "Fiat", "Ford", "Honda", "Hummer", "Hyundai", "Jaguar", "Jeep", "KIA", "Koenigsegg", "Lada", "Lamborghini", "Lancia", "Land Rover", "Lexus", "Ligier", "Lincoln", "Lotus", "Martini", "Maserati", "Maybach", "Mazda", "McLaren", "Mercedes-Benz", "Mini", "Mitsubishi", "Nissan", "Noble", "Opel", "Peugeot", "Pontiac", "Porsche", "Renault", "Rolls-Royce", "Rover", "Saab", "Seat", "Skoda", "Smart", "Spyker", "Subaru", "Suzuki", "Toyota", "Vauxhall", "Volkswagen", "Volvo", "Outro"]

@login_required
def home(request):
   return render(request, "home.html", {})

@login_required
def add(request):
    if request.method == "POST":
        plate = request.POST.get('plate', False)
        
        email = request.POST.get('email', False)
        nif = request.POST.get('nif', False)
        # name = request.POST.get('name', False)
        
        car = None
        client = None
        
        if (plate):
            try:
                car = Car.objects.get(plate__iexact=plate)
            except Car.DoesNotExist:
                carForm = CarForm(request.POST)
                try:
                    if carForm.is_valid():
                        car = carForm.save()
                    else:
                        print('Car form is not valid')
                        print(carForm.errors)
                except Exception as e:
                    print(e)
                    pass
        
        if (email or nif):
            try:
                if (nif):
                    client = Client.objects.get(nif__iexact = nif)
                else:
                    client = Client.objects.get(email__iexact = email)
            except Client.DoesNotExist:
                clientForm = ClientForm(request.POST)
                try:
                    if clientForm.is_valid():
                        client = clientForm.save()
                    else:
                        print('Client form is not valid')
                        print(clientForm.errors)
                except Exception as e:
                    print(e)
                    pass

        washForm = WashForm(request.POST)
        if washForm.is_valid():
            try:  
                wash = washForm.save(commit=False)  
                wash.car = car
                wash.client = client
                wash = washForm.save()  
                return redirect('/show')  
            except Exception as e:
                print(e)
                pass
        else:
            print("\nForms are not valid.\n")
            print(washForm.errors)
    
    paymentType = PaymentType.objects.get(name='Dinheiro')
    clientType = ClientType.objects.get(name='Cliente Premium')
    serviceType = ServiceType.objects.get(name='Completa')
    carType = CarType.objects.get(name='Ligeiro')

    washForm = WashForm(initial = {'paymentType' : paymentType.id, 'clientType' : clientType.id, 'serviceType' : serviceType.id})
    clientForm = ClientForm()
    carForm = CarForm(initial = {'carType' : carType.id})
    return render(request, "add.html", {'carBrands' : getCarBrands() , 'dateStr': getCurrentDate() , 'washForm' : washForm, 'clientForm' : clientForm, 'carForm': carForm, 'washModel' : Wash() })

@login_required
def show(request):  
    washes = Wash.objects.all()  
    return render(request,"show.html",{'washes' : washes})  

@login_required
def edit(request, id):
    try:
        wash = Wash.objects.get(id=id)  
        form = WashForm(instance = wash)  
    except Wash.DoesNotExist:
        return redirect("/add")
    return render(request,'edit.html', {'wash' : wash, 'washForm' : form})  

@login_required
def update(request, id):
    try:
        wash = Wash.objects.get(id=id)
        values = QueryDict(mutable=True)
        values.update(request.POST)
        values.update({'car': wash.car.id})
        if wash.car != None:
            values.update({'car': wash.car.id})
        if wash.client != None:
            values.update({'client': wash.client.id})
        form = WashForm(values, instance = wash)
        if form.is_valid():
            form.save()  
            return redirect("/show")
        else:
            print(form.errors)
    except Wash.DoesNotExist:
        pass
    return redirect("/edit/" + id)  

@login_required
def delete(request, id):  
    wash = Wash.objects.get(id=id)  
    wash.delete()  
    return redirect("/show")

@login_required
def editCar(request, id):
    try:
        car = Car.objects.get(id=id)  
        form = CarForm(instance = car)  
    except Car.DoesNotExist:
        return redirect("/add")
    return render(request,'editCar.html', {'carBrands' : getCarBrands(), 'car' : car, 'carForm' : form})  

@login_required
def editClient(request, id):
    try:
        client = Client.objects.get(id=id)  
        form = ClientForm(instance = client)  
    except Client.DoesNotExist:
        return redirect("/add")
    return render(request,'editClient.html', {'client' : client, 'clientForm' : form})  

@login_required
def updateCar(request, id):
    try:
        car = Car.objects.get(id=id)
        form = CarForm(request.POST, instance = car)
        if form.is_valid():
            form.save()  
            return redirect("/show")
        else:
            print(form.errors)
    except Car.DoesNotExist:
        pass
    return redirect("/edit/car/" + id)

@login_required
def updateClient(request, id):
    try:
        client = Client.objects.get(id=id)
        form = ClientForm(request.POST, instance = client)
        if form.is_valid():
            form.save()  
            return redirect("/show")
        else:
            print(form.errors)
    except Client.DoesNotExist:
        pass
    return redirect("/edit/client/" + id)

@login_required
def health(request):
    return HttpResponse(PageView.objects.count())

@login_required
def bootstrapHome(request):
   return render(request, "home_test.html", {})

def price(request,serviceTypeId, clientTypeId, carTypeId):
    priceObj = Price.objects.get(carType_id=carTypeId,serviceType_id=serviceTypeId,clientType_id=clientTypeId)
    responseData = {
        'price': priceObj.price,
        'clientTypeId': clientTypeId,
        'serviceTypeId' : serviceTypeId,
        'carTypeId' : carTypeId,
    }
    return JsonResponse(responseData)

linewashapp/templates/edit.html
<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="https://django-ex.web.cern.ch/assets/images/favicon.png">
      <title>Checkout example for Bootstrap</title>
      {% load staticfiles %} 
      <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/checkout/">
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <!-- Custom styles for this template -->
      <link href="https://getbootstrap.com/docs/4.0/examples/checkout/form-validation.css" rel="stylesheet">

      <link href="https://django-ex.web.cern.ch/assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
   </head>
   <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/">Line-Wash</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/add">Adicionar <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href="/show">Lista</a>
             </li>
            <li class="nav-item">
              <a class="nav-link" href="/accounts/login">🔲</a>
            </li><li class="nav-item">
              <a class="nav-link" href="/accounts/logout">🔳</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>
    <br>
   <body class="bg-light">
      <div class="container">
         <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="52" height="52">
            <h3>Editar lavagem</h3>
            <p class="lead">Insert or modify data in the form below.</p>
         </div>
         <div class="row">
            <div class="col-md-8 order-md-1">
               <!-- <h4 class="mb-3">Adicionar</h4> -->
               <form method="POST" class="needs-validation" action="/update/{{ wash.id}}/" novalidate>
                  {% csrf_token %}  
                <div class="row">
                     
                     <!-- <div class="form-group">
                        <label for="dtp_input1" class="col-md-2 control-label">DateTime Picking</label>
                        <div class="input-group date form_datetime col-md-5" data-date="" data-date-format="dd-mm-yyyy - hh:ii" data-link-field="dtp_input1">
                           <input class="form-control" size="16" type="text" value="" readonly>
                           <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                           <span class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
                        </div>
                        <input type="hidden" id="dtp_input1" value="" /><br/>
                     </div> -->
                     <!-- style = "width:500%;" -->
                     <div class="col-md-6 mb-3">
                        <label for="id_timestamp">Data/Hora</label>
                        <input type="text" class="form-control form_datetime"  placeholder="" value="{{ wash.timestamp|date:'Y-m-d H:i' }}" autocomplete="off">
                        <div class="invalid-feedback">
                           Valid first name is required.
                        </div>
                     </div>
                     <input type="hidden" id="id_timestamp" value="{{ wash.timestamp|date:'Y-m-d H:i' }}" name="timestamp" readonly/>

                     <div class="col-md-6 mb-3">
                        <label for="{{ washForm.price.id_for_label }}">Preço €</label>
                        <input type="text" class="form-control" name="price" id="{{ washForm.price.id_for_label }}" placeholder="€" value="{{ wash.price }}" required>
                        <div class="invalid-feedback">
                           Valid last name is required.
                        </div>
                     </div>
                  </div>
                  <div class="mb-3">
                     <label for="{{ washForm.tip.id_for_label }}">Tip<span class="text-muted"> (Optional)</span></label>
                     <input type="text" class="form-control" name="tip" id="{{ washForm.tip.id_for_label }}" placeholder="0 €" value="{% if not wash.tip %} 0 {% else %} {{ wash.tip }} {% endif %} ">
                     <div class="invalid-feedback">
                       Tip
                     </div>
                  </div>
                  <div class="custom-control custom-checkbox">
                      <input type="checkbox" class="custom-control-input" name="finalClient" id="{{ washForm.finalClient.id_for_label }}" {% if wash.finalClient %} checked {% endif %}>
                      <label class="custom-control-label" for="{{ washForm.finalClient.id_for_label }}">Cliente final</label>
                   </div>
                   <hr class="mb-4">
                  <button class="btn btn-primary btn-lg btn-block" type="submit">Gravar</button>
               </form>
               {% if wash.car or wash.client %}
                  <hr>
                  {% if wash.car %}
                  <a class="btn btn-outline-secondary" href="\edit\car\{{ wash.car.id }}">Editar Carro</a>
                  {% endif %}
                  {% if wash.client %}
                  <a class="btn btn-outline-secondary" href="\edit\client\{{ wash.client.id }}">Editar Cliente</a>
                  {% endif %}
               {% endif %}
            </div>
         </div>
         <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">&copy; 2019-2020 Line Wash</p>
            <ul class="list-inline">
               <li class="list-inline-item"><a href="#">Privacy</a></li>
               <li class="list-inline-item"><a href="#">Terms</a></li>
               <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
         </footer>
      </div>
      <!-- Bootstrap core JavaScript
         ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
      <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/holder.min.js"></script>
      <script>
         // Example starter JavaScript for disabling form submissions if there are invalid fields
         (function() {
           'use strict';
         
           window.addEventListener('load', function() {
             // Fetch all the forms we want to apply custom Bootstrap validation styles to
             var forms = document.getElementsByClassName('needs-validation');
         
             // Loop over them and prevent submission
             var validation = Array.prototype.filter.call(forms, function(form) {
               form.addEventListener('submit', function(event) {
                 if (form.checkValidity() === false) {
                   event.preventDefault();
                   event.stopPropagation();
                 }
                 form.classList.add('was-validated');
               }, false);
             });
           }, false);
         })();
      </script>
   </body>

   <script type="text/javascript" src="https://django-ex.web.cern.ch/assets/libs/bootstrap-datepicker/bootstrap-datetimepicker.min.js" charset="UTF-8"></script>
   <script type="text/javascript" src="https://django-ex.web.cern.ch/assets/libs/bootstrap-datepicker/bootstrap-datetimepicker.pt.js" charset="UTF-8"></script>
   <script type="text/javascript">
       $('.form_datetime').datetimepicker({
         language:  'pt',
         format: "yyyy-mm-dd hh:ii",
         weekStart: 1,
         todayBtn:  1,
         autoclose: 1,
         todayHighlight: 1,
         startView: 2,
         forceParse: 0,
         showMeridian: 0,
         minView: 1,
         linkField: "id_timestamp",
         linkFormat: "yyyy-mm-dd hh:ii"
       });
   </script>

</html>

linewashapp/templates/editCar.html
<!doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="https://django-ex.web.cern.ch/assets/images/favicon.png">
      <title>Checkout example for Bootstrap</title>
      {% load staticfiles %} 
      <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/checkout/">
      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <!-- Custom styles for this template -->
      <link href="https://getbootstrap.com/docs/4.0/examples/checkout/form-validation.css" rel="stylesheet">
      <link href="https://django-ex.web.cern.ch/assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
   </head>
   <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
         <a class="navbar-brand" href="/">Line-Wash</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
               <li class="nav-item">
                  <a class="nav-link" href="/">Home</a>
               </li>
               <li class="nav-item active">
                  <a class="nav-link" href="/add">Adicionar <span class="sr-only">(current)</span></a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="/show">Lista</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="/accounts/login">🔲</a>
                </li><li class="nav-item">
                  <a class="nav-link" href="/accounts/logout">🔳</a>
                </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0">
               <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
               <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
         </div>
      </nav>
   </header>
   <br>
   <body class="bg-light">
      <div class="container">
         <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="52" height="52">
            <h3>Editar Carro</h3>
            <p class="lead">Insert or modify data in the form below.</p>
         </div>
         <div class="row">
            <div class="col-md-8 order-md-1">
               <form method="POST" class="needs-validation" action="/update/car/{{ car.id }}/" novalidate>
                  {% csrf_token %}
                  <div class="col-md-3 mb-3">
                     <label for="{{ carForm.plate.id_for_label }}">Matricula</label>
                     <input type="text" class="form-control" name="plate" id="{{ carForm.plate.id_for_label }}" placeholder="XX-XX-XX" required value="{{ car.plate }}">
                     <div class="invalid-feedback">
                        Plate required.
                     </div>
                  </div>
                  <div class="col-md-5 mb-3">
                     <label for="{{ carForm.brand.id_for_label }}">Marca</label>
                     <select class="custom-select d-block w-100" name="brand" id="{{ carForm.brand.id_for_label }}" value="{{ car.brand }}">
						<option value="" disabled hidden>Choose...</option>
						{% for brand in carBrands %}
						   <option value="{{ brand }}" {% if brand == car.brand %} selected {% endif %}>{{ brand }}</option>
						   {% endfor %}
                     </select>
                     <div class="invalid-feedback">
                        Please select a valid brand.
                     </div>
                  </div>
                  <div class="col-md-4 mb-3">
                     <label for="{{ carForm.model.id_for_label }}">Modelo</label>
                     <input type="text" class="form-control" name="model" id="{{ carForm.model.id_for_label }}" placeholder="" value="{{ car.model }}">
                  </div>
                  
                  <hr class="mb-4">
                  <button class="btn btn-primary btn-lg btn-block" type="submit">Gravar</button>
               </form>
            </div>
         </div>
         <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">&copy; 2019-2020 Line Wash</p>
            <ul class="list-inline">
               <li class="list-inline-item"><a href="#">Privacy</a></li>
               <li class="list-inline-item"><a href="#">Terms</a></li>
               <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
         </footer>
      </div>
      <!-- Bootstrap core JavaScript
         ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
      <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/holder.min.js"></script>
      <script>
         // Example starter JavaScript for disabling form submissions if there are invalid fields
         (function() {
           'use strict';
         
           window.addEventListener('load', function() {
             // Fetch all the forms we want to apply custom Bootstrap validation styles to
             var forms = document.getElementsByClassName('needs-validation');
         
             // Loop over them and prevent submission
             var validation = Array.prototype.filter.call(forms, function(form) {
               form.addEventListener('submit', function(event) {
                 if (form.checkValidity() === false) {
                   event.preventDefault();
                   event.stopPropagation();
                 }
                 form.classList.add('was-validated');
               }, false);
             });
           }, false);
         })();
      </script>
   </body>
</html>